// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodeHunterWebAPI.Persistence;

#nullable disable

namespace NodeHunterWebAPI.Persistence.Migrations
{
    [DbContext(typeof(DbNodeHunterContext))]
    [Migration("20230825014442_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NodeHunterWebAPI.Entities.TabCliente", b =>
                {
                    b.Property<int>("codigoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoCliente"));

                    b.Property<int>("codigoUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("isEmissor")
                        .HasColumnType("bit");

                    b.Property<string>("loginName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigoCliente");

                    b.ToTable("tabCliente");
                });

            modelBuilder.Entity("NodeHunterWebAPI.Entities.TabDocumento", b =>
                {
                    b.Property<int>("codigoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoDocumento"));

                    b.Property<int>("clientecodigoCliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("emissorcodigoEmissor")
                        .HasColumnType("int");

                    b.Property<bool>("isCanceled")
                        .HasColumnType("bit");

                    b.Property<bool>("isOpen")
                        .HasColumnType("bit");

                    b.HasKey("codigoDocumento");

                    b.HasIndex("clientecodigoCliente");

                    b.HasIndex("emissorcodigoEmissor");

                    b.ToTable("tabDocumento");
                });

            modelBuilder.Entity("NodeHunterWebAPI.Entities.TabEmissor", b =>
                {
                    b.Property<int>("codigoEmissor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoEmissor"));

                    b.Property<int>("codigoUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("isEmissor")
                        .HasColumnType("bit");

                    b.Property<string>("loginName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigoEmissor");

                    b.ToTable("tabEmissors");
                });

            modelBuilder.Entity("NodeHunterWebAPI.Entities.TabItemDocumento", b =>
                {
                    b.Property<int>("codigoDocumento")
                        .HasColumnType("int");

                    b.Property<int>("codigoItemDocumento")
                        .HasColumnType("int");

                    b.Property<int>("tabObjetocodigoObjeto")
                        .HasColumnType("int");

                    b.Property<int>("tabPermissaocodigoPermissao")
                        .HasColumnType("int");

                    b.HasKey("codigoDocumento", "codigoItemDocumento");

                    b.HasIndex("tabObjetocodigoObjeto");

                    b.HasIndex("tabPermissaocodigoPermissao");

                    b.ToTable("tabItemDocumento");
                });

            modelBuilder.Entity("NodeHunterWebAPI.Entities.TabObjeto", b =>
                {
                    b.Property<int>("codigoObjeto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoObjeto"));

                    b.Property<int>("codigoBancoDados")
                        .HasColumnType("int");

                    b.Property<int>("codigoSchema")
                        .HasColumnType("int");

                    b.Property<string>("descricaoTipoObjeto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigoObjeto");

                    b.ToTable("tabObjeto");
                });

            modelBuilder.Entity("NodeHunterWebAPI.Entities.TabPermissao", b =>
                {
                    b.Property<int>("codigoPermissao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigoPermissao"));

                    b.Property<string>("descricaoPermissao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigoPermissao");

                    b.ToTable("tabPermissao");
                });

            modelBuilder.Entity("NodeHunterWebAPI.Entities.TabDocumento", b =>
                {
                    b.HasOne("NodeHunterWebAPI.Entities.TabCliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clientecodigoCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NodeHunterWebAPI.Entities.TabEmissor", "emissor")
                        .WithMany()
                        .HasForeignKey("emissorcodigoEmissor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cliente");

                    b.Navigation("emissor");
                });

            modelBuilder.Entity("NodeHunterWebAPI.Entities.TabItemDocumento", b =>
                {
                    b.HasOne("NodeHunterWebAPI.Entities.TabDocumento", null)
                        .WithMany("tabItemDocumentos")
                        .HasForeignKey("codigoDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NodeHunterWebAPI.Entities.TabObjeto", "tabObjeto")
                        .WithMany()
                        .HasForeignKey("tabObjetocodigoObjeto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NodeHunterWebAPI.Entities.TabPermissao", "tabPermissao")
                        .WithMany()
                        .HasForeignKey("tabPermissaocodigoPermissao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tabObjeto");

                    b.Navigation("tabPermissao");
                });

            modelBuilder.Entity("NodeHunterWebAPI.Entities.TabDocumento", b =>
                {
                    b.Navigation("tabItemDocumentos");
                });
#pragma warning restore 612, 618
        }
    }
}
